### ISSUE TITLE
Remove dist directory from repo and add to .gitignore

### ISSUE THREAD

**Issue by seanmadi** [ammuench/node-artifact-api#4]
I haven't used typescript too much, but I think you only need that for building and deploying to npm.

**Comment by seanmadi** [comment]
I'd also recommend removing `package-lock.json` from .gitignore.

**Comment by ammuench** [comment]
Will address and clean these up soon

**Comment by ammuench** [comment]
Fixed in [v0.2.1](https://github.com/ammuench/node-artifact-api/releases/tag/v0.2.1)
