### ISSUE TITLE
have you worked on encoding?

### ISSUE THREAD

**Issue by ohjinsoo** [ammuench/node-artifact-api#6]
Hello, I am working with a friend in making a React + Electron application for Artifact and I am using your API. I noticed in your README that it says that you have not started the deck encoder. As it seems to be a simple (yet tedious) task in just translating Valve's PHP deck_encoder into Typescript, do you mind if I do it? If you have started on encoding but noticed anything I'd have to look out for, please let me know in advance.

Thank you.

**Comment by ammuench** [comment]
Hey @ohjinsoo!  I have not had a chance to start work on the encoder, and would be incredibly happy to let you take a crack at it.  Based on my work with the decoder, you should just have to switch over the encoder from PHP into JS/TS.  

A couple of notes from when I worked on the decoder that might help:

* PHP allows parameters passed in with an `&` to be edited within the function they're passed into.  There are a couple of ways around this in JS--either passing in params as part of an array/object so the same thing can occur, or returning new values from the function editing them, and assigning them after those functions are called.  I went with the second flow as it was slightly easier for me to manage in my mind, but I've seen other implementations where things were passed in with the object/array style notation.  There are a lot of times where the decoder would call a function that returned a boolean alone in the conditional to see if the code failed, but it would also update index, card count, etc if it didn't

* I used the qunpack library in the decoder, which was helpful.  I also read up a bit on buffers in JS as well, which helped out a lot

* Just disable TS for the bulk of the encoder logic when you start, it'll save the headache down the line haha

**Comment by ohjinsoo** [comment]
Alright, I'll try it out either tonight or tomorrow. Thanks for your tips!

**Comment by ohjinsoo** [comment]
Hey @ammuench, So I think I got the easy part down, replacing all the PHP syntax and whatnot. A couple notes though:

- In EncodeBytes, I have to create the $name variable outside of the if statement otherwise it won't exist after it exits the scope of the if statement. This means that in Line 412 of my file, $name will either be "" or $deckContents['name'].replace(/(<([^>]+)>)/ig,""), which is the equivalent of PHP's strip_tags ( [I think](https://stackoverflow.com/questions/5601903/jquery-almost-equivalent-of-phps-strip-tags) ). I'm not sure if I did this the way Valve's encoder would run, but just making a note in case I did it incorrectly.
- I'm not sure if I called unpack() correctly at Line 413. You wrote a wrapper function called unpackArray, but not sure if you have to do that here as well.
- qunpack doesn't support pack() yet, so I found this instead: http://locutus.io/php/misc/pack/. it gives an example "pack('nvc*', 0x1234, 0x5678, 65, 66)" and in encoder they pass "...$bytes" as you can see in line 429. So pack should be just fine.
- I also used http://locutus.io/php/url/base64_encode/ for the base64_encode you have to do at Line 432.
- In line 433, they have "this.$sm_rgchEncodedPrefix . $encoded". I'm not familiar with PHP, so I wasn't sure what this meant, so I left it alone.

Hope I helped a little bit at least lol.  

[ohjinsoo_encoder.txt](https://github.com/ammuench/node-artifact-api/files/2609339/ohjinsoo_encoder.txt)

**Comment by ammuench** [comment]
@ohjinsoo if you could fork this repo, make a `feature/encoder` branch, and then open a PR to master it would be much easier to assess and review.  If you need help, reach out to me here or via email and I can set some time to walk you through it.

As for your pack replacement, I will trust your judgement on it.  If it seems to work, run with it 😺

**Comment by artbarte** [comment]
I have successfully ported encoder without any library.  If I fully done it and fully documentated it, I'll open the PR.

**Comment by artbarte** [comment]
By the way, if you wouldn't mind I would love to help you with your application. @ohjinsoo

**Comment by ammuench** [comment]
As of [`v0.4.0`](https://github.com/ammuench/node-artifact-api/releases/tag/v0.4.0) release, encoding is now fully integrated!

Thank you @artbarte and @ohjinsoo for your help!

**Comment by AonanLi** [comment]
Hi there, I tried to decode in React Native, but it returned invalid result. I'm sure it should run correctly in a normal web browser. Just seems to be not working on react-native somehow

**Comment by ammuench** [comment]
@AonanLi can you please test with the following code?

`ADCJaQnJ7kCAhaDSLhdbd0Bh6UBpAE6ARJTQ4qxAYaabQFLb3ptaWMgLSBQYXRoIG9mIHRoZSAgQ3VubmluZyBDaGFsbGVuZ2U_`

If that still returns invalid, please go add
`console.trace(e)` before line 16 in `dist/modules/decks.js` and let me know what the stack trace is when you run it

**Comment by AonanLi** [comment]
Still invalid, tried tracing the error but somehow I didn't see the log message in my console. 

My guess is there's something wrong with this function:
https://github.com/ammuench/node-artifact-api/blob/a5004da804c601929c4b5ac0c9b9f6c4eb5b56f7/src/modules/decoder.ts#L80

I tried the other library which didn't work in the beginning. Then I figured out it's because react-native doesn't have `window.atob` 
https://github.com/bubblebooy/ArtifactDeckCode/blob/893f70907c1e5134afe6999e441053142416c358/deck_decoder.js#L24

After replacing `window.atob` with [base64](https://www.npmjs.com/package/base64), that library worked. I guess we are having a similar issue here with `qunpack.unpack`

**Comment by ammuench** [comment]
Hrm, I don't think qunpack has any window dependencies.  Given that I can
run it as a standalone node application I imagine that wouldn't be the
issue?

I will look into this when I get home today.  In the meantime maybe try
importing ArtifactDeckDecoder directly (it's exported in index) and seeing
if you can trace a better error?

**Comment by AonanLi** [comment]
```
import { ArtifactDeckDecoder } from '../../../node_modules/node-artifact-api';
const deckDecoder = new ArtifactDeckDecoder();
console.log(
    deckDecoder.ParseDeck(
        'ADCJaQnJ7kCAhaDSLhdbd0Bh6UBpAE6ARJTQ4qxAYaabQFLb3ptaWMgLSBQYXRoIG9mIHRoZSAgQ3VubmluZyBDaGFsbGVuZ2U_'
    )
);
```

Throw error: "Can't find variable: Buffer"

https://github.com/facebook/react-native/issues/14796

**Comment by ammuench** [comment]
Huzzah!  Feel free to add that in and try it out.  I will update and push a
new build of the package when I'm off work tonight

**Comment by ammuench** [comment]
@AonanLi should be fixed in `v0.4.1` https://github.com/ammuench/node-artifact-api/releases/tag/v0.4.1

**Comment by AonanLi** [comment]
Thanks! Just tested with `ADCJWkTZX05uwGDCRV4XQGy3QGLmqUBg4GQJgGLGgO7AaABR3JlZW4vQmxhY2sgRXhhbXBsZQ__`

Here's the result:

```
Object {
  "cards": Array [
    Object {
      "count": 2,
      "id": 3000,
    },
    Object {
      "count": 1,
      "id": 3001,
    },
    Object {
      "count": 3,
      "id": 10091,
    },
    Object {
      "count": 3,
      "id": 10102,
    },
    Object {
      "count": 3,
      "id": 10128,
    },
    Object {
      "count": 3,
      "id": 10165,
    },
    Object {
      "count": 3,
      "id": 10168,
    },
    Object {
      "count": 3,
      "id": 10169,
    },
    Object {
      "count": 3,
      "id": 10185,
    },
    Object {
      "count": 1,
      "id": 10223,
    },
    Object {
      "count": 3,
      "id": 10234,
    },
    Object {
      "count": 1,
      "id": 10260,
    },
    Object {
      "count": 1,
      "id": 10263,
    },
    Object {
      "count": 3,
      "id": 10322,
    },
    Object {
      "count": 3,
      "id": 10354,
    },
  ],
  "heroes": Array [
    Object {
      "id": 4005,
      "turn": 2,
    },
    Object {
      "id": 10014,
      "turn": 1,
    },
    Object {
      "id": 10017,
      "turn": 3,
    },
    Object {
      "id": 10026,
      "turn": 1,
    },
    Object {
      "id": 10047,
      "turn": 1,
    },
  ],
  "name": "Green/Black Example",
}
```

It returns the same result as the other library, but not quite correct. There are only 27 cards shown for the main deck. Cards such as "No Accident" are not in the result.

**Comment by AonanLi** [comment]
Think I fugured out why. Those 15 hero reference cards are not in the result. I should add them by myself.

Thanks very much for the work done!
